### ISSUE TITLE
CreatureUnique and list (question)

### ISSUE THREAD

**Issue by Tutul-** [Immudelki/IFSCL_CODE#1]
Hi, thanks for your code example :D I was waiting for that for a long time ^^"

But on line 9 you use a list : 
`public static List<CreatureUnique>liste=new List<CreatureUnique>();`

I assume that CreatureUnique know every instance of himslef. Can you describe why ?
That can be usefull but that can be a strange way to design too in some case.

Thanks again for you work <3

**Comment by Immudelki** [comment]
Well there's no direct use between the other creatureUnique but I had to put the list that references them all -somewhere-, in which case I prefer it to be on the corresponding class itself.
Does that make sense ?

**Comment by Tutul-** [comment]
a different approach may be a controller that keep track on every entity. They are different ways to achieve a specific goal. You pick one, I describe an other. I have no claim on who has the best solution ;)
